### ISSUE TITLE
Issue with the walktrhough

### ISSUE THREAD

**Issue by Jymms** [RedGreenCode/UWP#2]
From https://www.redgreencode.com/mvvm-fundamentals-uwp-apps/
[
Here are the steps to create TaskViewModel:

In the UWPMain project: Add — New Folder — ViewModels
In the Models folder: Add — Class — NotificationBase.cs
In the Models folder: Add — Class — TaskViewModel.cs
]

Why create the ViewModels Folder then put the .cs in the Models folder?

**Comment by RedGreenCode** [comment]
Good catch, that's a typo. Everything in those steps should refer to the ViewModels folder. I corrected the blog post.
